#!/usr/bin/env bash
set -e
ROOT=$(pwd)
shellcheck ./install
shellcheck ./check
if [ "$1" != "" ]; then
    cd "$1"
    shellcheck ./install
else
  for dir in */; do
      echo -n "-------- $dir"
      cd "$dir"
      (shellcheck ./install && echo " OK") || echo
      cd "$ROOT"
  done
fi
