#!/usr/bin/env bash
set -e

ROOT=$(pwd)

ask() {
    read -p "$1 (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi
}

if [ "$1" != "" ]; then
    ask "Continue installing $1?"
    cd "$1" && bash ./install
else
  ask "Are you sure you would like to install everything?"
  for dir in */; do
      cd "-------- $dir"
      bash ./install
      cd "$ROOT"
  done
fi