[[language]]
name = "ocaml"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "rust"
auto-format = true